#!/usr/bin/env bash
# End-to-end check of the game archive routes against a running backend.
# Proves a real GameRecord round-trips: POST it, GET it back, compare.
# Usage: bash scripts/smoke-games.sh [base-url]
set -uo pipefail

BASE="${1:-http://localhost:8787}"
KEY="${API_KEY:-WARNING_DEV_API_KEY_DO_NOT_USE_IN_PRODUCTION}"
pass=0
fail=0

check() { # check <label> <expected> <actual>
    if [ "$2" = "$3" ]; then
        echo "  ok   $1 ($3)"
        pass=$((pass + 1))
    else
        echo "  FAIL $1 — expected $2, got $3"
        fail=$((fail + 1))
    fi
}

# The record is generated by the same fixture the unit tests use, so this
# exercises a record the game's own GameRecordSchema accepts rather than a
# hand-written approximation that has drifted.
GAME_ID="Smk$(printf '%05d' $((RANDOM % 100000)))"
RECORD=$(npx tsx -e "
import { buildGameRecord } from './src/services/gameRecordFixture.ts';
import { replacer } from '@game/Util.ts';
process.stdout.write(
  JSON.stringify(buildGameRecord({ gameID: '${GAME_ID}' }), replacer),
);
" 2> /dev/null)

[ -n "$RECORD" ] || {
    echo "could not build the fixture record"
    exit 1
}
echo "record built: $(printf '%s' "$RECORD" | wc -c) bytes, game ${GAME_ID}"

post() { # post <game-id> <api-key> <body-file>
    curl -s -m 20 -o /dev/null -w '%{http_code}' -X POST "$BASE/game/$1" \
        -H 'Content-Type: application/json' -H "x-api-key: $2" \
        --data-binary "@$3"
}

PSQL="docker compose exec -T postgres psql -qtAX -U openfront -d openfront -c"

# The fixture's first player carries this persistentID. Seeding a matching
# account makes the linking path real: that player must end up with a user_id,
# while the guest and the disconnected player must not. Without the seed the
# "guests stay null" check would pass trivially, because nothing would link.
FIXTURE_PID="3f7a1c2e-8b4d-4e5f-9a6b-0c1d2e3f4a5b"
$PSQL "insert into users (id, public_id) values ('$FIXTURE_PID', 'smoke-archive')
       on conflict (id) do nothing" > /dev/null 2>&1

BODY=$(mktemp)
GOT=$(mktemp)
GOT2=$(mktemp)
printf '%s' "$RECORD" > "$BODY"
trap 'rm -f "$BODY" "$GOT" "$GOT2"' EXIT

echo "1. POST requires the api key"
check "no key rejected" "401" \
    "$(curl -s -m 20 -o /dev/null -w '%{http_code}' -X POST "$BASE/game/$GAME_ID" \
        -H 'Content-Type: application/json' --data-binary "@$BODY")"
check "wrong key rejected" "401" "$(post "$GAME_ID" "nope" "$BODY")"

echo "2. first POST archives the record"
check "created" "201" "$(post "$GAME_ID" "$KEY" "$BODY")"

echo "3. re-POSTing the same id is an upsert, not a conflict"
check "second write accepted" "200" "$(post "$GAME_ID" "$KEY" "$BODY")"

echo "4. GET returns the record — and it still validates"
curl -s -m 20 "$BASE/game/$GAME_ID" -H "x-api-key: $KEY" > "$GOT"
# Value-identical, not byte-identical: jsonb does not preserve key order, and
# ingest maps the "" persistentID the game server writes for a disconnected
# player to null. Everything else must come back exactly as it went in, which
# is what a replay depends on.
check "round-trips unchanged for the game server" "yes" \
    "$(npx tsx -e "
import { readFileSync } from 'node:fs';
import { GameRecordSchema } from '@game/Schemas.ts';
import { normalizeEmptyPersistentIds } from './src/services/games.ts';
const sort = (v) => Array.isArray(v) ? v.map(sort)
  : v && typeof v === 'object'
    ? Object.fromEntries(Object.keys(v).sort().map((k) => [k, sort(v[k])]))
    : v;
const sent = normalizeEmptyPersistentIds(JSON.parse(process.argv[1]));
const got = JSON.parse(readFileSync(process.argv[2], 'utf8'));
const ok = JSON.stringify(sort(sent)) === JSON.stringify(sort(got))
  && GameRecordSchema.safeParse(got).success;
process.stdout.write(ok ? 'yes' : 'no');
" "$RECORD" "$GOT" 2> /dev/null)"

echo "5. an unauthenticated GET (the browser replay path) hides the PII"
curl -s -m 20 "$BASE/game/$GAME_ID" > "$GOT2"
check "no persistentID leaks" "yes" \
    "$(grep -q '3f7a1c2e-8b4d-4e5f-9a6b-0c1d2e3f4a5b' "$GOT2" && echo no || echo yes)"
check "still parses as a GameRecord (replays keep working)" "yes" \
    "$(npx tsx -e "
import { readFileSync } from 'node:fs';
import { GameRecordSchema } from '@game/Schemas.ts';
const got = JSON.parse(readFileSync(process.argv[1], 'utf8'));
const r = GameRecordSchema.safeParse(got);
process.stdout.write(r.success ? 'yes' : 'no');
" "$GOT2" 2> /dev/null)"
# The turns ARE the replay. Every turn number, intent and hash must survive.
check "turns survive intact for the replay" "yes" \
    "$(npx tsx -e "
import { readFileSync } from 'node:fs';
const sort = (v) => Array.isArray(v) ? v.map(sort)
  : v && typeof v === 'object'
    ? Object.fromEntries(Object.keys(v).sort().map((k) => [k, sort(v[k])]))
    : v;
const sent = JSON.parse(process.argv[1]);
const got = JSON.parse(readFileSync(process.argv[2], 'utf8'));
process.stdout.write(
  JSON.stringify(sort(sent.turns)) === JSON.stringify(sort(got.turns))
    ? 'yes' : 'no',
);
" "$RECORD" "$GOT2" 2> /dev/null)"

echo "6. participants were flattened out of the blob"
# Straight from Postgres: the point of the table is that player history never
# has to open games.record. Two of the three players share the username
# "Player", so a name-keyed table would only have kept one of them.
ROWS=$($PSQL "select count(*) from game_participants where game_id='$GAME_ID'" 2> /dev/null | tr -d ' \r')
check "one row per player, duplicate names included" "3" "$ROWS"
LINKED=$($PSQL "select count(*) from game_participants where game_id='$GAME_ID' and user_id='$FIXTURE_PID'" 2> /dev/null | tr -d ' \r')
check "the player with an account is linked to it" "1" "$LINKED"
# The guest (null persistentID) and the player who disconnected (empty one).
GUESTS=$($PSQL "select count(*) from game_participants where game_id='$GAME_ID' and user_id is null" 2> /dev/null | tr -d ' \r')
check "guests recorded, just without an account" "2" "$GUESTS"
NAMED=$($PSQL "select count(*) from game_participants where game_id='$GAME_ID' and player_name='Player'" 2> /dev/null | tr -d ' \r')
check "both players sharing a username survived" "2" "$NAMED"
WON=$($PSQL "select count(*) from game_participants where game_id='$GAME_ID' and won" 2> /dev/null | tr -d ' \r')
check "exactly one winner" "1" "$WON"
STATS=$($PSQL "select count(*) from game_participants where game_id='$GAME_ID' and stats is not null" 2> /dev/null | tr -d ' \r')
check "stats copied out for every player" "3" "$STATS"
# The upsert must not duplicate rows: step 3 POSTed the same game twice.
GAMES=$($PSQL "select count(*) from games where id='$GAME_ID'" 2> /dev/null | tr -d ' \r')
check "one games row after two POSTs" "1" "$GAMES"
COMMIT=$($PSQL "select git_commit from games where id='$GAME_ID'" 2> /dev/null | tr -d ' \r')
check "git_commit promoted to a column" "$(printf 'a%.0s' $(seq 40))" "$COMMIT"

echo "7. unknown game"
check "404 for a game never archived" "404" \
    "$(curl -s -m 20 -o /dev/null -w '%{http_code}' "$BASE/game/Zzz99999")"

echo "8. malformed id and body"
check "bad game id rejected" "400" \
    "$(curl -s -m 20 -o /dev/null -w '%{http_code}' "$BASE/game/not-an-id")"
check "garbage body rejected" "400" \
    "$(curl -s -m 20 -o /dev/null -w '%{http_code}' -X POST "$BASE/game/$GAME_ID" \
        -H 'Content-Type: application/json' -H "x-api-key: $KEY" \
        -d '{"version":"v0.0.2"}')"

echo "9. a record whose id disagrees with the URL"
check "id mismatch rejected" "400" \
    "$(curl -s -m 20 -o /dev/null -w '%{http_code}' -X POST "$BASE/game/Aaa11111" \
        -H 'Content-Type: application/json' -H "x-api-key: $KEY" \
        --data-binary "@$BODY")"

echo
echo "passed $pass, failed $fail"
[ "$fail" -eq 0 ]
