"""
Build the Landtaker logo pack and social media kit from the master SVGs.

Everything downstream of brand/images/logo/*.svg is generated by this script —
nothing in dist/ is hand-edited, so a change to a master SVG only needs a rerun.

Run:  python brand/src/make_logo_pack.py
Out:  brand/dist/
"""
import io
import os
import re
import sys

import resvg_py
from PIL import Image, ImageChops, ImageDraw

HERE = os.path.dirname(os.path.abspath(__file__))
BRAND = os.path.dirname(HERE)
SRC = os.path.join(BRAND, "images", "logo")
OUT = os.path.join(BRAND, "dist")

# Palette. The mark uses light for outlines/rims, ink for fills, orange as the
# single accent; slate only appears in a few hairline seams.
LIGHT = "#e8ecef"
INK = "#0d1013"
ORANGE = "#ff8a1f"
SLATE = "#333c45"

# Raster sizes per lockup. Long-form lockups need more pixels to keep the
# wordmark legible, so each variant carries its own list rather than one shared
# set of squares.
SIZES = {
    "mark": [64, 128, 256, 512, 1024],
    "lockup-horizontal": [400, 800, 1600, 2400],
    "lockup-stacked": [300, 600, 1200, 1800],
    "wordmark": [400, 800, 1600, 2400],
}

FAVICON_SIZES = [16, 32, 48, 64, 128, 180, 192, 512]


def render(svg_text, width=None, height=None, background=None):
    """SVG string -> PIL RGBA image."""
    raw = resvg_py.svg_to_bytes(
        svg_string=svg_text,
        width=width,
        height=height,
        background=background,
        shape_rendering="geometric_precision",
    )
    if isinstance(raw, list):
        raw = bytes(raw)
    return Image.open(io.BytesIO(raw)).convert("RGBA")


# --------------------------------------------------------------------------
# Colour variants
#
# The mark is not a flat shape: LIGHT draws the outlines and rims, INK fills the
# body. Recolouring every path to a single value collapses those two roles and
# the mark turns into a blob, so the mono variants below keep the light paths as
# holes instead of painting over them.
# --------------------------------------------------------------------------

def recolor(svg, mapping):
    """Replace fill="#xxx" values according to mapping (case-insensitive)."""
    def sub(m):
        val = m.group(1).lower()
        return 'fill="%s"' % mapping.get(val, m.group(1))

    return re.sub(r'fill="(#[0-9a-fA-F]{6})"', sub, svg)


def variant_color(svg):
    """The master artwork, untouched."""
    return svg


def variant_on_light(svg):
    """
    For light backgrounds: swap the light and ink roles.

    Swapping both ways matters. Recolouring only the light paths to ink — the
    obvious reading of "make it work on white" — turns the shield into a solid
    black slab, because the ink paths that were the fill stay ink and swallow
    the map seams and the rocket. Trading the two roles keeps the plate light
    and the detail dark, so the artwork still reads.

    A hand-authored master takes precedence over this where one exists; see
    ON_LIGHT_MASTERS.
    """
    return recolor(svg, {
        LIGHT.lower(): INK,
        INK.lower(): LIGHT,
        SLATE.lower(): INK,
    })


# Hand-authored light versions, preferred over the generated swap above. The
# horizontal lockup has one because the automatic swap cannot decide which of
# two ink paths is plate and which is detail — a person drew that distinction
# deliberately, and it looks better than anything the recolour produces.
ON_LIGHT_MASTERS = {
    "lockup-horizontal": "lockup-horizontal-light.svg",
}


def variant_mono(svg, color):
    """
    Single-colour silhouette with cut-outs.

    Naively flattening every path to one colour welds the outlines to the fill
    and the mark reads as a blob, so this keeps the two roles apart:

      * the SHAPE is the union of every path — including the light ones, which
        is what keeps the crown (it sits outside the shield and has no ink
        beneath it) and the rocket from disappearing;
      * the light paths are then punched back out, but only where ink lies
        underneath, which is what preserves the map seams as negative space.

    Punching the light paths out unconditionally was the first attempt and it
    deleted the crown outright.
    """
    silhouette = recolor(svg, {
        INK.lower(): color,
        ORANGE.lower(): color,
        SLATE.lower(): color,
        LIGHT.lower(): color,
    })
    holes = recolor(svg, {
        INK.lower(): "none",
        ORANGE.lower(): "none",
        SLATE.lower(): "none",
        LIGHT.lower(): color,
    })
    body = recolor(svg, {
        INK.lower(): color,
        ORANGE.lower(): color,
        SLATE.lower(): color,
        LIGHT.lower(): "none",
    })
    return silhouette, holes, body


def render_mono(svg, color, width):
    """Render a mono variant to RGBA, doing the cut-out in pixel space."""
    silhouette, holes, body = variant_mono(svg, color)

    sil = render(silhouette, width=width)
    hole = render(holes, width=width).split()[3]
    bod = render(body, width=width).split()[3]

    # A light path only becomes a hole where the body actually covers it.
    # Elsewhere (the crown, the rocket tip) it has to stay solid.
    cut = ImageChops.multiply(hole, bod)
    alpha = ImageChops.subtract(sil.split()[3], cut)

    out = Image.new("RGBA", sil.size, color)
    out.putalpha(alpha)
    return out


def mono_svg(svg, color):
    """
    Vector form of the mono variant.

    Same two-layer idea as render_mono, expressed as a mask: the silhouette is
    painted in `color`, then the light paths are removed through a luminance
    mask that is itself clipped to the body. Keeping it as a mask means the
    SVG stays resolution-independent instead of baking in a rasterised cut.
    """
    def inner(s):
        return re.sub(r'^.*?<svg[^>]*>|</svg>\s*$', '', s, flags=re.S)

    head = re.match(r'<svg[^>]*>', svg).group(0)

    # Mirrors render_mono exactly: alpha = silhouette - (holes AND body).
    #
    # The subtraction has to be gated on the body, because a light path with
    # nothing beneath it is structure, not a seam — the crown sits entirely
    # outside the shield and an ungated cut deletes it. Nesting the mask does
    # the gating: `cut` paints the light paths white, but is itself masked by
    # `bodyonly`, so it can only remove pixels the body actually covers.
    white = "#ffffff"
    black = "#000000"

    solid = inner(recolor(svg, {
        INK.lower(): color, ORANGE.lower(): color,
        SLATE.lower(): color, LIGHT.lower(): color,
    }))
    body_white = inner(recolor(svg, {
        INK.lower(): white, ORANGE.lower(): white,
        SLATE.lower(): white, LIGHT.lower(): "none",
    }))
    light_white = inner(recolor(svg, {
        INK.lower(): "none", ORANGE.lower(): "none",
        SLATE.lower(): "none", LIGHT.lower(): white,
    }))

    return (
        '%s<defs>'
        '<mask id="ltbody" maskUnits="userSpaceOnUse">%s</mask>'
        '<mask id="ltmono" maskUnits="userSpaceOnUse">'
        '<rect x="-100%%" y="-100%%" width="300%%" height="300%%" fill="%s"/>'
        '<g fill="%s">%s</g>'
        '<g mask="url(#ltbody)">%s</g>'
        '</mask>'
        '</defs>'
        '<g mask="url(#ltmono)">%s</g></svg>'
        % (
            head,
            body_white,
            black,
            white,
            # Silhouette: every path, so the crown counts as shape.
            inner(recolor(svg, {
                INK.lower(): white, ORANGE.lower(): white,
                SLATE.lower(): white, LIGHT.lower(): white,
            })),
            # Cut: light paths in black, gated to the body by ltbody.
            inner(recolor(svg, {
                INK.lower(): "none", ORANGE.lower(): "none",
                SLATE.lower(): "none", LIGHT.lower(): black,
            })),
            solid,
        )
    )


VARIANTS = {
    "color": variant_color,
    "on-light": variant_on_light,
    "mono-light": lambda s: mono_svg(s, LIGHT),
    "mono-ink": lambda s: mono_svg(s, INK),
}

# Mono PNGs go through render_mono instead of rendering the mask SVG, so the
# cut-out is identical whichever way a consumer picks the file up.
MONO_COLORS = {"mono-light": LIGHT, "mono-ink": INK}


# --------------------------------------------------------------------------
# Wordmark extraction
#
# The wordmark exists only as a <g> inside the horizontal lockup. Pulling it out
# means keeping that group, dropping the mark, and re-fitting the viewBox to what
# is left — the group's own transform tells us where it sits.
# --------------------------------------------------------------------------

def extract_wordmark(lockup_svg):
    m = re.search(
        r'<g fill="([^"]+)" transform="translate\(([\d.]+) ([\d.]+)\) scale\(([\d.]+)\)">(.*?)</g>',
        lockup_svg,
        re.S,
    )
    if not m:
        raise SystemExit("wordmark group not found in lockup-horizontal.svg")

    fill, group = m.group(1), m.group(0)

    # Tight bounds come from a probe render rather than from parsing the path
    # data: the glyphs use quadratic segments whose control points sit outside
    # the ink, so arithmetic on the coordinate list clips the outer letters.
    # Rendering once over the parent viewBox and reading the alpha bbox is exact.
    vb = re.search(r'viewBox="([\d.\- ]+)"', lockup_svg).group(1).split()
    px, py, pw, ph = (float(v) for v in vb)

    probe_w = 2000
    probe = (
        '<svg xmlns="http://www.w3.org/2000/svg" viewBox="%s" width="%d" fill="none">%s</svg>'
        % (" ".join(vb), probe_w, group)
    )
    bbox = render(probe, width=probe_w).split()[3].getbbox()
    if bbox is None:
        raise SystemExit("wordmark probe rendered empty")

    # Probe pixels -> parent user units.
    upp = pw / probe_w
    vb_x = px + bbox[0] * upp
    vb_y = py + bbox[1] * upp
    vb_w = (bbox[2] - bbox[0]) * upp
    vb_h = (bbox[3] - bbox[1]) * upp

    pad = vb_h * 0.08
    vb_x -= pad
    vb_y -= pad
    vb_w += pad * 2
    vb_h += pad * 2

    width = 1200
    height = max(1, round(width * vb_h / vb_w))

    return (
        '<svg xmlns="http://www.w3.org/2000/svg" '
        'viewBox="%.2f %.2f %.2f %.2f" width="%d" height="%d" fill="none">%s</svg>'
        % (vb_x, vb_y, vb_w, vb_h, width, height, group)
    )


def favicon_simplified(svg):
    """
    A reduced cut of the mark for 16px-class favicons.

    Keeps the shield plate and the orange territory and drops everything that
    cannot survive the downscale: the map seams, the rocket, the mushroom cloud
    and the hairline slate seams. The result is the same silhouette and the same
    accent, which is what a favicon actually needs to be identifiable.
    """
    head = re.match(r'<svg[^>]*>', svg).group(0)
    paths = re.findall(r'<path[^>]*/>', svg)

    def bbox(p):
        nums = [float(v) for v in re.findall(r'(-?\d+\.?\d*)', re.search(r'd="([^"]*)"', p).group(1))]
        xs, ys = nums[0::2], nums[1::2]
        return min(xs), min(ys), max(xs), max(ys)

    def area(p):
        x0, y0, x1, y1 = bbox(p)
        return (x1 - x0) * (y1 - y0)

    # The shield plate is simply the largest light path — it spans the whole
    # mark, where every other light path is an interior detail (rocket body,
    # fins, crown). Picking "the first light path" happens to work today but
    # breaks the moment the master is re-exported in a different order.
    light_paths = [p for p in paths if LIGHT in p]
    shield = max(light_paths, key=area)

    # Both orange paths together make the territory; they are contiguous.
    territory = [p for p in paths if ORANGE in p]

    # The plate has to keep its real colouring — dark face, light rim — or the
    # favicon reads as a light badge and stops matching the full logo. The rim
    # is produced by drawing the same outline twice: once in light as the
    # backing, once in ink shrunk about its own centre, leaving the difference
    # visible as an edge.
    x0, y0, x1, y1 = bbox(shield)
    cx, cy = (x0 + x1) / 2, (y0 + y1) / 2
    k = 0.955  # rim weight; thick enough to hold up at 16px

    rim = shield
    face = shield.replace(
        'fill="%s"' % LIGHT, 'fill="%s"' % INK
    ).replace(
        'transform="translate(0,0)"',
        'transform="translate(%.2f %.2f) scale(%.4f)"' % (cx * (1 - k), cy * (1 - k), k),
    )

    return head + rim + face + "".join(territory) + "</svg>"


# --------------------------------------------------------------------------
# Social kit
# --------------------------------------------------------------------------

# `fit` is the box the logo is scaled into, as a fraction of the canvas. Given
# per-axis because a lockup on a tall canvas is limited by width and a mark on a
# wide one by height — a single number makes the logo shrink on both.
SOCIAL = [
    # (name, width, height, logo, (fit_w, fit_h), note)
    ("avatar-400",        400,  400,  "mark", (0.74, 0.74), "Discord / X / generic"),
    ("avatar-512",        512,  512,  "mark", (0.74, 0.74), "Steam / YouTube"),
    ("avatar-1024",      1024, 1024,  "mark", (0.74, 0.74), "high-dpi source"),
    ("og-1200x630",      1200,  630,  "lockup-horizontal", (0.68, 0.46), "Open Graph / link preview"),
    ("x-banner",         1500,  500,  "lockup-horizontal", (0.52, 0.56), "X / Twitter header"),
    # Scaled against the safe box below, not the full canvas.
    ("youtube-banner",   2048, 1152,  "lockup-horizontal", (0.74, 0.64), "YouTube channel art"),
    ("discord-banner",    960,  540,  "lockup-horizontal", (0.68, 0.48), "Discord server banner"),
    ("post-square",      1080, 1080,  "lockup-stacked", (0.66, 0.60), "Instagram / feed"),
    ("post-story",       1080, 1920,  "lockup-stacked", (0.72, 0.40), "Story / Shorts / Reels"),

    # Reddit. The icons render inside a circular clip, so they use the same
    # centred mark as the other avatars but with a smaller fit — the corners of
    # a square-fitted mark would be shaved off by the crop.
    ("reddit-icon-256",   256,  256,  "mark", (0.62, 0.62), "subreddit icon (circular crop)"),
    ("reddit-icon-512",   512,  512,  "mark", (0.62, 0.62), "subreddit icon, high-dpi"),
    ("reddit-header",     256,   64,  "lockup-horizontal", (0.86, 0.70), "old.reddit header"),
    # Reddit overlays the subreddit name and icon across the left of the banner,
    # so the artwork is pushed right instead of centred.
    ("reddit-banner",    1920,  384,  "lockup-horizontal", (0.34, 0.52), "community banner"),
    ("reddit-banner-sm", 1920,  256,  "lockup-horizontal", (0.34, 0.56), "community banner, short"),
]

# YouTube crops its banner hard on small screens; everything essential has to sit
# inside a 1546x423 box centred on the canvas. The logo is fitted to that box
# rather than to the 2048x1152 canvas, otherwise it renders correctly on desktop
# and gets cropped away on phones.
YT_SAFE = {"youtube-banner": (1546, 423)}

# Horizontal placement, as a fraction of the free space: 0.0 hard left, 0.5
# centred, 1.0 hard right. Reddit puts its own chrome over the left third of a
# community banner, so the logo sits right of it rather than underneath.
ALIGN_X = {
    "reddit-banner": 0.72,
    "reddit-banner-sm": 0.72,
}

# Assets Reddit displays inside a circle. Rendered square, but checked against
# the inscribed circle so nothing important is lost to the clip.
CIRCLE_CROP = {"reddit-icon-256", "reddit-icon-512"}


def compose(logo_img, w, h, fit, bg, accent=None, backdrop=None, safe=None, align_x=0.5):
    """Place the logo on a canvas, fitted into `fit` (fraction of w, of h)."""
    canvas = Image.new("RGBA", (w, h), bg)

    if backdrop is not None:
        canvas.alpha_composite(fit_cover(backdrop, w, h))

    if accent is not None:
        canvas.alpha_composite(accent)

    canvas.alpha_composite(*place(logo_img, w, h, fit, safe, align_x))
    return canvas


def place(logo_img, w, h, fit, safe=None, align_x=0.5):
    """Scale the logo into the fit box and return (image, top-left offset)."""
    # On a platform with a crop-safe area the logo is fitted to that box, so it
    # survives the crop; elsewhere the full canvas is the reference.
    ref_w, ref_h = safe if safe else (w, h)

    fw, fh = fit
    lw, lh = logo_img.size
    scale = min(ref_w * fw / lw, ref_h * fh / lh)
    nw, nh = max(1, round(lw * scale)), max(1, round(lh * scale))

    resized = logo_img.resize((nw, nh), Image.LANCZOS)
    return resized, (round((w - nw) * align_x), (h - nh) // 2)


def check_circle_safe(path, name):
    """
    Assert the artwork in `path` survives a circular clip.

    Compares the mark against the inscribed circle and reports how much ink
    falls outside it. Anything above a hair of antialiasing means the corners
    get shaved off once Reddit applies its own mask.
    """
    im = Image.open(path).convert("RGBA")
    w, h = im.size
    r = min(w, h) / 2.0
    cx, cy = w / 2.0, h / 2.0

    mask = Image.new("L", (w, h), 0)
    ImageDraw.Draw(mask).ellipse([cx - r, cy - r, cx + r, cy + r], fill=255)

    # Ink = anything visibly different from the flat background, sampled from a
    # corner that the circle never covers.
    bg = im.getpixel((0, 0))
    ink = Image.new("L", (w, h), 0)
    ipx = ink.load()
    src = im.load()
    outside = 0
    total = 0
    mpx = mask.load()
    for y in range(h):
        for x in range(w):
            p = src[x, y]
            if abs(p[0] - bg[0]) + abs(p[1] - bg[1]) + abs(p[2] - bg[2]) > 24:
                total += 1
                ipx[x, y] = 255
                if mpx[x, y] == 0:
                    outside += 1

    if total == 0:
        raise SystemExit("%s: rendered empty" % name)

    pct = outside * 100.0 / total
    if pct > 0.5:
        raise SystemExit(
            "%s: %.1f%% of the mark falls outside the circular crop — "
            "reduce its fit fraction" % (name, pct)
        )
    print("  %s: %.2f%% outside circle (ok)" % (name, pct))


def fit_cover(img, w, h):
    """Scale-and-crop `img` to exactly w x h, preserving aspect."""
    iw, ih = img.size
    scale = max(w / iw, h / ih)
    nw, nh = max(1, round(iw * scale)), max(1, round(ih * scale))
    r = img.resize((nw, nh), Image.LANCZOS)
    return r.crop(((nw - w) // 2, (nh - h) // 2, (nw - w) // 2 + w, (nh - h) // 2 + h))


def accent_bar(w, h):
    """A thin orange rule along the bottom edge — the one brand accent."""
    layer = Image.new("RGBA", (w, h), (0, 0, 0, 0))
    bar = max(3, round(h * 0.012))
    layer.paste(Image.new("RGBA", (w, bar), ORANGE), (0, h - bar))
    return layer


def load_backdrop():
    """
    The map render used behind the 'map' social set.

    Dimmed hard: at full strength the terrain competes with the mark, and the
    whole point of a backdrop here is texture, not subject matter.
    """
    path = os.path.join(BRAND, "..", "resources", "images", "EuropeBackground.webp")
    path = os.path.normpath(path)
    if not os.path.exists(path):
        return None

    bd = Image.open(path).convert("RGBA")
    dim = Image.new("RGBA", bd.size, (13, 16, 19, 205))
    bd.alpha_composite(dim)
    return bd


# --------------------------------------------------------------------------

def w(path):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    return path


def on_light_svg(lockup, svg):
    """The light-background artwork: hand-authored master if there is one."""
    fname = ON_LIGHT_MASTERS.get(lockup)
    if fname:
        path = os.path.join(SRC, fname)
        if os.path.exists(path):
            with open(path, encoding="utf-8") as f:
                return f.read()
    return svg if lockup == "wordmark" else variant_on_light(svg)


def main():
    masters = {}
    for name in ("mark", "lockup-horizontal", "lockup-stacked"):
        with open(os.path.join(SRC, name + ".svg"), encoding="utf-8") as f:
            masters[name] = f.read()

    masters["wordmark"] = extract_wordmark(masters["lockup-horizontal"])

    written = 0

    # ---- SVG + PNG variants -------------------------------------------------
    for lockup, svg in masters.items():
        for vname, fn in VARIANTS.items():
            # A wordmark has no fills to lose, so on-light/mono collapse to a
            # plain recolour of the single glyph group.
            if lockup == "wordmark":
                colors = {"color": LIGHT, "on-light": INK, "mono-light": LIGHT, "mono-ink": INK}
                out_svg = recolor(svg, {LIGHT.lower(): colors[vname]})
            elif vname == "on-light":
                out_svg = on_light_svg(lockup, svg)
            else:
                out_svg = fn(svg)

            svg_path = w(os.path.join(OUT, "svg", lockup, "%s-%s.svg" % (lockup, vname)))
            with open(svg_path, "w", encoding="utf-8") as f:
                f.write(out_svg)
            written += 1

            for size in SIZES[lockup]:
                if vname in MONO_COLORS and lockup != "wordmark":
                    img = render_mono(svg, MONO_COLORS[vname], size)
                else:
                    img = render(out_svg, width=size)
                png_path = w(os.path.join(OUT, "png", lockup, "%s-%s-%dw.png" % (lockup, vname, size)))
                img.save(png_path, "PNG", optimize=True)
                written += 1

    print("logo variants: %d files" % written)

    # ---- Favicons -----------------------------------------------------------
    # Below ~24px the full mark stops resolving: the map seams, the rocket and
    # the mushroom cloud all land inside a couple of pixels and average into
    # mush. The small sizes therefore use a reduced cut — shield plus the orange
    # territory, nothing else — which is still recognisably the same logo at
    # tab size. Anything 32px and up keeps the full artwork.
    fav_svg = masters["mark"]
    fav_small = favicon_simplified(fav_svg)

    fav_imgs = []
    for size in FAVICON_SIZES:
        src = fav_small if size < 32 else fav_svg
        img = render(src, width=size)
        img.save(w(os.path.join(OUT, "favicon", "favicon-%d.png" % size)), "PNG", optimize=True)
        if size in (16, 32, 48):
            fav_imgs.append(img)

    with open(w(os.path.join(OUT, "favicon", "favicon-small.svg")), "w", encoding="utf-8") as f:
        f.write(fav_small)

    # Apple touch icons must be opaque — iOS composites them onto white
    # otherwise, and the dark mark on white loses its outlines.
    apple = render(fav_svg, width=180, background=INK)
    apple.save(w(os.path.join(OUT, "favicon", "apple-touch-icon.png")), "PNG", optimize=True)

    fav_imgs[0].save(
        w(os.path.join(OUT, "favicon", "favicon.ico")),
        format="ICO",
        sizes=[(16, 16), (32, 32), (48, 48)],
    )
    print("favicons: %d files" % (len(FAVICON_SIZES) + 2))

    # ---- Social kit ---------------------------------------------------------
    backdrop = load_backdrop()
    if backdrop is None:
        print("warning: EuropeBackground.webp missing — skipping the map set")

    # Render each lockup once at high resolution and downscale per target;
    # re-rendering the SVG per social asset would be slower for no gain.
    hi = {k: render(v, width=3000) for k, v in masters.items()}

    # The on-light recolour, rendered once per lockup rather than per target.
    hi_light = {
        k: render(on_light_svg(k, v), width=3000)
        for k, v in masters.items()
    }

    social_count = 0
    for name, sw, sh, lockup, fit, note in SOCIAL:
        safe = YT_SAFE.get(name)
        ax = ALIGN_X.get(name, 0.5)

        # A circular-crop asset gets no accent rule: the bar runs along the
        # bottom edge of the square and the clip removes all but its middle,
        # which reads as a stray orange smudge rather than a deliberate rule.
        bar = None if name in CIRCLE_CROP else accent_bar(sw, sh)

        # Plain set: mark on brand ink, orange rule at the foot.
        plain = compose(hi[lockup], sw, sh, fit, INK, accent=bar, safe=safe, align_x=ax)
        plain.save(w(os.path.join(OUT, "social", "plain", name + ".png")), "PNG", optimize=True)
        social_count += 1

        # Light set: the on-light variant so the mark reads against #e8ecef.
        light = compose(hi_light[lockup], sw, sh, fit, LIGHT, accent=bar, safe=safe, align_x=ax)
        light.save(w(os.path.join(OUT, "social", "light", name + ".png")), "PNG", optimize=True)
        social_count += 1

        if backdrop is not None:
            mapped = compose(
                hi[lockup], sw, sh, fit, INK,
                accent=bar, backdrop=backdrop, safe=safe, align_x=ax,
            )
            mapped.save(w(os.path.join(OUT, "social", "map", name + ".png")), "PNG", optimize=True)
            social_count += 1

            # The og card is also the link preview the game server serves, and
            # only brand/images/ is published as an asset root — dist/ is not.
            # Writing it here keeps the served copy from going stale when a
            # master SVG changes.
            if name == "og-1200x630":
                mapped.save(
                    w(os.path.join(BRAND, "images", "social", name + ".png")),
                    "PNG", optimize=True,
                )
                social_count += 1

        # Transparent: same geometry, no canvas — for dropping onto anything.
        canvas = Image.new("RGBA", (sw, sh), (0, 0, 0, 0))
        canvas.alpha_composite(*place(hi[lockup], sw, sh, fit, safe, ax))
        canvas.save(w(os.path.join(OUT, "social", "transparent", name + ".png")), "PNG", optimize=True)
        social_count += 1

    print("social: %d files" % social_count)

    # Reddit clips its icons to a circle. Verify the artwork actually survives
    # that clip rather than trusting the fit fraction — a mark that overflows
    # the inscribed circle loses its corners in the live UI, where it is too
    # late to notice.
    for name in sorted(CIRCLE_CROP):
        check_circle_safe(os.path.join(OUT, "social", "plain", name + ".png"), name)

    print("done -> %s" % OUT)


if __name__ == "__main__":
    main()
